/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2022-07-07 21:34:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/vku/ktx/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/test/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1655716260513L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&amp;display=swap\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://mdbootstrap.com/api/snippets/static/download/MDB5-Free_4.2.0/css/mdb.min.css\" />\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"./favicons/favicon.ico\">\r\n");
      out.write("<link rel=\"./faviconsapple-touch-icon\" sizes=\"180x180\"\r\n");
      out.write("	href=\"./favicons/apple-touch-icon.png\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"32x32\"\r\n");
      out.write("	href=\"./favicons/favicon-32x32.png\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"16x16\"\r\n");
      out.write("	href=\"./favicons/favicon-16x16.png\">\r\n");
      out.write("<title>Hệ thống quản lý ký túc xá</title>\r\n");
      out.write("<style>\r\n");
      out.write(".modal-content {\r\n");
      out.write("	position: static;\r\n");
      out.write("	float: left;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	width: 1000px;\r\n");
      out.write("	background: #ffffff;\r\n");
      out.write("	box-shadow: 0px 3px 6px rgb(34 25 25/ 40%);\r\n");
      out.write("	padding: 0px 30px;\r\n");
      out.write("	min-height: 100%;\r\n");
      out.write("	cursor: default;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	background-color: #fbfbfb;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( min-width : 991.98px) {\r\n");
      out.write("	main {\r\n");
      out.write("		padding-left: 240px;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Sidebar */\r\n");
      out.write(".sidebar {\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	bottom: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	padding: 58px 0 0; /* Height of navbar */\r\n");
      out.write("	box-shadow: 0 2px 5px 0 rgb(0 0 0/ 5%), 0 2px 10px 0 rgb(0 0 0/ 5%);\r\n");
      out.write("	width: 240px;\r\n");
      out.write("	z-index: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width : 991.98px) {\r\n");
      out.write("	.sidebar {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .active {\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	box-shadow: 0 2px 5px 0 rgb(0 0 0/ 16%), 0 2px 10px 0 rgb(0 0 0/ 12%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar-sticky {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	height: calc(100vh - 48px);\r\n");
      out.write("	padding-top: 0.5rem;\r\n");
      out.write("	overflow-x: hidden;\r\n");
      out.write("	overflow-y: auto;\r\n");
      out.write("	/* Scrollable contents if viewport is shorter than content. */\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!--Main Navigation-->\r\n");
      out.write("	<header>\r\n");
      out.write("		<!-- Sidebar -->\r\n");
      out.write("		<nav id=\"sidebarMenu\"\r\n");
      out.write("			class=\"collapse d-lg-block sidebar collapse bg-white\">\r\n");
      out.write("			<div class=\"position-sticky\">\r\n");
      out.write("				<div class=\"list-group list-group-flush mx-3 mt-4\">\r\n");
      out.write("					<!-- Collapse 1 -->\r\n");
      out.write("					<a class=\"list-group-item list-group-item-action py-2 ripple\"\r\n");
      out.write("						aria-current=\"true\" data-mdb-toggle=\"collapse\"\r\n");
      out.write("						href=\"#collapseExample1\" aria-expanded=\"true\"\r\n");
      out.write("						aria-controls=\"collapseExample1\"> <i\r\n");
      out.write("						class=\"fa-solid fa-bars-progress\"></i> <span>Quản lý</span>\r\n");
      out.write("					</a>\r\n");
      out.write("					<!-- Collapsed content -->\r\n");
      out.write("					<ul id=\"collapseExample1\"\r\n");
      out.write("						class=\"collapse show list-group list-group-flush\">\r\n");
      out.write("						<li class=\"list-group-item py-1\"><a href=\"quanlySV\"\r\n");
      out.write("							class=\"text-reset\"> <i class=\"fa-solid fa-graduation-cap\"></i>\r\n");
      out.write("								Quản lý sinh viên\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"list-group-item py-1\"><a href=\"quanlyPhong\"\r\n");
      out.write("							class=\"text-reset\"> <i class=\"fa-solid fa-building-lock\"></i>\r\n");
      out.write("								Quản lý phòng\r\n");
      out.write("						</a></li>\r\n");
      out.write("						<li class=\"list-group-item py-1\"><a href=\"quanlyAcc\"\r\n");
      out.write("							class=\"text-reset\"> <i class=\"fa-solid fa-key\"></i> Quản lý\r\n");
      out.write("								tài khoản\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<!-- Collapse 1 -->\r\n");
      out.write("\r\n");
      out.write("					<!-- Collapse 2 -->\r\n");
      out.write("					<a class=\"list-group-item list-group-item-action py-2 ripple\"\r\n");
      out.write("						aria-current=\"true\" data-mdb-toggle=\"collapse\"\r\n");
      out.write("						href=\"#collapseExample2\" aria-expanded=\"true\"\r\n");
      out.write("						aria-controls=\"collapseExample2\"> <i\r\n");
      out.write("						class=\"fas fa-chart-area fa-fw me-3\"></i><span> <i\r\n");
      out.write("							class=\"fa-solid fa-wave-pulse\"></i> Hành động\r\n");
      out.write("					</span>\r\n");
      out.write("					</a>\r\n");
      out.write("					<!-- Collapsed content -->\r\n");
      out.write("					<ul id=\"collapseExample2\"\r\n");
      out.write("						class=\"collapse list-group list-group-flush\">\r\n");
      out.write("						<li class=\"list-group-item py-1\"><a href=\"layDSCanDuyetPhong\"\r\n");
      out.write("							class=\"text-reset\"> <i class=\"fa-solid fa-circle-check\"></i>\r\n");
      out.write("								Duyệt đăng ký phòng\r\n");
      out.write("						</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<!-- Collapse 2 -->\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</nav>\r\n");
      out.write("		<!-- Sidebar -->\r\n");
      out.write("\r\n");
      out.write("		<!-- Navbar -->\r\n");
      out.write("		<nav id=\"main-navbar\"\r\n");
      out.write("			class=\"navbar navbar-expand-lg navbar-light bg-white fixed-top\">\r\n");
      out.write("			<!-- Container wrapper -->\r\n");
      out.write("			<div class=\"container-fluid\">\r\n");
      out.write("				<!-- Toggle button -->\r\n");
      out.write("				<button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("					data-mdb-toggle=\"collapse\" data-mdb-target=\"#sidebarMenu\"\r\n");
      out.write("					aria-controls=\"sidebarMenu\" aria-expanded=\"false\"\r\n");
      out.write("					aria-label=\"Toggle navigation\">\r\n");
      out.write("					<i class=\"fas fa-bars\"></i>\r\n");
      out.write("				</button>\r\n");
      out.write("\r\n");
      out.write("				<!-- Brand -->\r\n");
      out.write("				<a class=\"navbar-brand\" href=\"#\"> <img src=\"./images/vku.png\"\r\n");
      out.write("					height=\"25\" alt=\"\" loading=\"lazy\" />\r\n");
      out.write("				</a>\r\n");
      out.write("				<!-- Search form -->\r\n");
      out.write("				<form class=\"d-none d-md-flex input-group w-auto my-auto\">\r\n");
      out.write("					<input autocomplete=\"off\" type=\"search\"\r\n");
      out.write("						class=\"form-control rounded\" placeholder=\"\"\r\n");
      out.write("						style=\"min-width: 225px\" /> <span\r\n");
      out.write("						class=\"input-group-text border-0\"><i\r\n");
      out.write("						class=\"fas fa-search\"></i></span>\r\n");
      out.write("				</form>\r\n");
      out.write("\r\n");
      out.write("				<!-- Right links -->\r\n");
      out.write("				<ul class=\"navbar-nav ms-auto d-flex flex-row\">\r\n");
      out.write("					<!-- Notification dropdown -->\r\n");
      out.write("					<li class=\"nav-item dropdown\"><a\r\n");
      out.write("						class=\"nav-link me-3 me-lg-0 dropdown-toggle hidden-arrow\"\r\n");
      out.write("						href=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\"\r\n");
      out.write("						data-mdb-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("							<i class=\"fas fa-bell\"></i> <span\r\n");
      out.write("							class=\"badge rounded-pill badge-notification bg-danger\">1</span>\r\n");
      out.write("					</a>\r\n");
      out.write("						<ul class=\"dropdown-menu dropdown-menu-end\"\r\n");
      out.write("							aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"#\">Some news</a></li>\r\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"#\">Another news</a></li>\r\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"#\">Something else\r\n");
      out.write("									here</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("\r\n");
      out.write("					<!-- Icon -->\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link me-3 me-lg-0\" href=\"#\">\r\n");
      out.write("\r\n");
      out.write("					</a></li>\r\n");
      out.write("					<!-- Icon -->\r\n");
      out.write("					<li class=\"nav-item me-3 me-lg-0\"><a class=\"nav-link\" href=\"#\">\r\n");
      out.write("\r\n");
      out.write("					</a></li>\r\n");
      out.write("\r\n");
      out.write("					<!-- Icon dropdown -->\r\n");
      out.write("					<li class=\"nav-item dropdown\"><a\r\n");
      out.write("						class=\"nav-link me-3 me-lg-0 dropdown-toggle hidden-arrow\"\r\n");
      out.write("						href=\"#\" id=\"navbarDropdown\" role=\"button\"\r\n");
      out.write("						data-mdb-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("							<i class=\"united kingdom flag m-0\"></i>\r\n");
      out.write("					</a>\r\n");
      out.write("						<ul class=\"dropdown-menu dropdown-menu-end\"\r\n");
      out.write("							aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"#\"><i\r\n");
      out.write("									class=\"united kingdom flag\"></i>Việt Nam <i\r\n");
      out.write("									class=\"fa fa-check text-success ms-2\"></i></a></li>\r\n");
      out.write("							<li><hr class=\"dropdown-divider\" /></li>\r\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"#\"><i\r\n");
      out.write("									class=\"poland flag\"></i>English</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("\r\n");
      out.write("					<!-- Avatar -->\r\n");
      out.write("					<li class=\"nav-item dropdown\"><a\r\n");
      out.write("						class=\"nav-link dropdown-toggle hidden-arrow d-flex align-items-center\"\r\n");
      out.write("						href=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\"\r\n");
      out.write("						data-mdb-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("							<img src=\"./images/sinhvien/21IT010.jpg\" class=\" rounded-circle\" height=\"22\" alt=\"\" loading=\"lazy\" />\r\n");
      out.write("					</a>\r\n");
      out.write("						<ul class=\"dropdown-menu dropdown-menu-end\"\r\n");
      out.write("							aria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("							<li><a class=\"dropdown-item\" href=\"#\">Logout</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Container wrapper -->\r\n");
      out.write("		</nav>\r\n");
      out.write("		<!-- Navbar -->\r\n");
      out.write("	</header>\r\n");
      out.write("	<!--Main Navigation-->\r\n");
      out.write("\r\n");
      out.write("	<!--Main layout-->\r\n");
      out.write("	<main style=\"margin-top: 58px\">\r\n");
      out.write("		<h1>\r\n");
      out.write("			<h3> Xin chào ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" ! </h3>\r\n");
      out.write("		</h1>\r\n");
      out.write("	</main>\r\n");
      out.write("	<!--Main layout-->\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\" src=\"js/min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\"\r\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
