/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2022-07-08 02:41:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_002dlive_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/vku/ktx/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/test/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1655716260513L));
    _jspx_dependants.put("/WEB-INF/style.css", Long.valueOf(1657208816345L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\" href=\"./favicons/favicon.ico\">\r\n");
      out.write("<link rel=\"./faviconsapple-touch-icon\" sizes=\"180x180\"\r\n");
      out.write("	href=\"./favicons/apple-touch-icon.png\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"32x32\"\r\n");
      out.write("	href=\"./favicons/favicon-32x32.png\">\r\n");
      out.write("<link rel=\"icon\" type=\"image/png\" sizes=\"16x16\"\r\n");
      out.write("	href=\"./favicons/favicon-16x16.png\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<style>");
      out.write("@import\r\n");
      out.write("	url('https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap')\r\n");
      out.write("	;\r\n");
      out.write("\r\n");
      out.write("html {\r\n");
      out.write("	scroll-behavior: smooth;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary {\r\n");
      out.write("	color: #fff !important;\r\n");
      out.write("	background-color: #FF6A3D !important;\r\n");
      out.write("	border-color: #FF6A3D !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2 {\r\n");
      out.write("	font-size: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".center {\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".preloading {\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	background: #ffffff no-repeat center center !important;\r\n");
      out.write("	background-size: 10%;\r\n");
      out.write("	z-index: 9999;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divider:after, .divider:before {\r\n");
      out.write("	content: \"\";\r\n");
      out.write("	flex: 1;\r\n");
      out.write("	height: 1px;\r\n");
      out.write("	background: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p {\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=submit] {\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span {\r\n");
      out.write("	color: red !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span {\r\n");
      out.write("	color: red;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-light .navbar-nav .nav-link, #navbarColor03>ul.nav.navbar-nav.navbar-right>li>a\r\n");
      out.write("	{\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul li a {\r\n");
      out.write("	font-family: \"bebasneue\", Tahoma, Arial, sans-serif !important;\r\n");
      out.write("	text-transform: uppercase;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbarColor03>ul.nav.navbar-nav.navbar-right>li>a>i:before {\r\n");
      out.write("	padding: 3px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbarColor03>form {\r\n");
      out.write("	width: 130px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbarColor03>form>div>a {\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover {\r\n");
      out.write("	text-decoration: none !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body>div>div>form>div>div:nth-child(4)>a {\r\n");
      out.write("	width: 370px;\r\n");
      out.write("	height: 29px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn:after {\r\n");
      out.write("	padding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-default {\r\n");
      out.write("	color: #ffffff;\r\n");
      out.write("	background-color: #a7a9aa;\r\n");
      out.write("	border-color: #a7a9aa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	height: 55px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	height: 45px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	background-size: 300% 100%;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	moz-transition: all .4s ease-in-out;\r\n");
      out.write("	-o-transition: all .4s ease-in-out;\r\n");
      out.write("	-webkit-transition: all .4s ease-in-out;\r\n");
      out.write("	transition: all .4s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn:hover {\r\n");
      out.write("	background-position: 100% 0;\r\n");
      out.write("	moz-transition: all .4s ease-in-out;\r\n");
      out.write("	-o-transition: all .4s ease-in-out;\r\n");
      out.write("	-webkit-transition: all .4s ease-in-out;\r\n");
      out.write("	transition: all .4s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn:focus {\r\n");
      out.write("	outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("	background-image: linear-gradient(to right, #f5ce62, #e43603, #fa7199, #e85a19);\r\n");
      out.write("	box-shadow: 0 4px 15px 0 rgba(229, 66, 10, 0.75);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal-content {\r\n");
      out.write("	position: static;\r\n");
      out.write("	float: left;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	width: 1000px;\r\n");
      out.write("	background: #ffffff;\r\n");
      out.write("	box-shadow: 0px 3px 6px rgb(34 25 25/ 40%);\r\n");
      out.write("	padding: 0px 30px;\r\n");
      out.write("	min-height: 100%;\r\n");
      out.write("	cursor: default;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".img-thumbnail {\r\n");
      out.write("	width: 100px;\r\n");
      out.write("	height: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Dashboard */\r\n");
      out.write("body {\r\n");
      out.write("	background-color: #fbfbfb;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( min-width : 991.98px) {\r\n");
      out.write("	main {\r\n");
      out.write("		padding-left: 240px;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Sidebar */\r\n");
      out.write(".sidebar {\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	bottom: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	padding: 58px 0 0; /* Height of navbar */\r\n");
      out.write("	box-shadow: 0 2px 5px 0 rgb(0 0 0/ 5%), 0 2px 10px 0 rgb(0 0 0/ 5%);\r\n");
      out.write("	width: 240px;\r\n");
      out.write("	z-index: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width : 991.98px) {\r\n");
      out.write("	.sidebar {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .active {\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	box-shadow: 0 2px 5px 0 rgb(0 0 0/ 16%), 0 2px 10px 0 rgb(0 0 0/ 12%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar-sticky {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	height: calc(100vh - 48px);\r\n");
      out.write("	padding-top: 0.5rem;\r\n");
      out.write("	overflow-x: hidden;\r\n");
      out.write("	overflow-y: auto;\r\n");
      out.write("	/* Scrollable contents if viewport is shorter than content. */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img.anhthe {\r\n");
      out.write("	width: 113px;\r\n");
      out.write("	height: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button {\r\n");
      out.write("	margin-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("hr {\r\n");
      out.write("	border: 1px solid blue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("	background-color: #fbfbfb;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=checkbox], input[type=radio] {\r\n");
      out.write("	/* box-sizing: border-box; */\r\n");
      out.write("	font-size: 5px;\r\n");
      out.write("	margin: 0 10px 0 10px;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	width: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	height: 33px !important;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	height: 45px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	background-size: 300% 100%;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	moz-transition: all .4s ease-in-out;\r\n");
      out.write("	-o-transition: all .4s ease-in-out;\r\n");
      out.write("	-webkit-transition: all .4s ease-in-out;\r\n");
      out.write("	transition: all .4s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn:hover {\r\n");
      out.write("	background-position: 100% 0;\r\n");
      out.write("	moz-transition: all .4s ease-in-out;\r\n");
      out.write("	-o-transition: all .4s ease-in-out;\r\n");
      out.write("	-webkit-transition: all .4s ease-in-out;\r\n");
      out.write("	transition: all .4s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn:focus {\r\n");
      out.write("	outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-success {\r\n");
      out.write("	background-image: linear-gradient(to right, #25aae1, #40e495, #30dd8a, #2bb673);\r\n");
      out.write("	box-shadow: 0 4px 15px 0 rgba(49, 196, 190, 0.75);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-default {\r\n");
      out.write("	background-image: linear-gradient(to right, #ed6ea0, #ec8c69, #f7186a, #FBB03B);\r\n");
      out.write("	box-shadow: 0 4px 15px 0 rgba(236, 116, 149, 0.75);\r\n");
      out.write("}\r\n");
      out.write("/* Dashboard */");
      out.write("</style>\r\n");
      out.write("<style>\r\n");
      out.write("table, td, th {\r\n");
      out.write("	border: 1px solid;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	border-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("$(function () {\r\n");
      out.write("    $(\"#datepicker1\").datepicker({\r\n");
      out.write("        dateFormat: \"dd/mm/yy\",\r\n");
      out.write("      });\r\n");
      out.write("    $(\"#datepicker2\").datepicker({\r\n");
      out.write("      dateFormat: \"dd/mm/yy\",\r\n");
      out.write("    });\r\n");
      out.write("  };\r\n");
      out.write("\r\n");
      out.write(" </script>\r\n");
      out.write("<title>Home</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- Preloading -->\r\n");
      out.write("	<div class=\"preloading\">\r\n");
      out.write("		<img src=\"gif/pre-loader.gif\" alt=\"\"\r\n");
      out.write("			style=\"width: 150px; height: auto;\">\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- nav starts  -->\r\n");
      out.write("\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-light sticky-top\"\r\n");
      out.write("		style=\"background-color: #0F2557;\">\r\n");
      out.write("		<a class=\"navbar-brand\" href=\"index.jsp\"><img src=\"images/vku.png\"\r\n");
      out.write("			alt=\"\" width=\"66px\" height=\"35px\"></a>\r\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("			data-target=\"#navbarColor03\" aria-controls=\"navbarColor03\"\r\n");
      out.write("			aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("		</button>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarColor03\">\r\n");
      out.write("			<ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"index.jsp\">Trang\r\n");
      out.write("						chủ</a></li>\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f6(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f7(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			");
      if (_jspx_meth_c_005fif_005f8(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<!-- nav end -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"site_content\" style=\"margin-top: 10px\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<section class=\"col-md-12\" id=\"searchDiv\">\r\n");
      out.write("					<div class=\"page_header cfix\" id=\"page_header\">\r\n");
      out.write("						<div class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12\"></div>\r\n");
      out.write("						<div class=\"container\">\r\n");
      out.write("							<div class=\"text-left\">\r\n");
      out.write("								<h2>Đăng ký ở nội trú</h2>\r\n");
      out.write("								<hr>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<div class=\"col-xs-11 col-sm-4 col-md-4 col-lg-3\">\r\n");
      out.write("									<input class=\"form-control\" name=\"masv\" id=\"masv\"\r\n");
      out.write("										placeholder=\"Mã sinh viên\" autocomplete=\"off\"\r\n");
      out.write("										required=\"required\" autofocus=\"1\" type=\"text\">\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<div class=\"col-xs-11 col-sm-4 col-md-4 col-lg-3\">\r\n");
      out.write("									<button class=\"btn btn-primary\" id=\"search\">\r\n");
      out.write("										<i class=\"fa-solid fa-magnifying-glass\"></i> Tìm kiếm\r\n");
      out.write("									</button>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div id=\"image_id\">\r\n");
      out.write("							<img id=\"ajax-loader\" class=\"img-responsive\"\r\n");
      out.write("								src=\"gif/ajax-loader.gif\" style=\"display: none;\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<br>\r\n");
      out.write("					<div id=\"info_student\"\r\n");
      out.write("						class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12\"></div>\r\n");
      out.write("				</section>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"center\" style=\"margin: 20 auto; width: 100%\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- <footer\r\n");
      out.write("  class=\"text-center text-white fixed-bottom\"\r\n");
      out.write("  style=\"background-color: white\"\r\n");
      out.write(">\r\n");
      out.write("  <div class=\"container p-4\"></div>\r\n");
      out.write("  <div class=\"text-center p-3\" style=\"background-color: rgba(0, 0, 0, 0.2)\">\r\n");
      out.write("    <span id=\"timeNow\"></span>\r\n");
      out.write("    <a class=\"text-white\" href=\"#\"></a>\r\n");
      out.write("  </div>\r\n");
      out.write("</footer> -->\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"js/script.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("	    function searchSVAjax() {\r\n");
      out.write("	        var masvSearch = document.getElementById('masv').value;\r\n");
      out.write("	        console.log(masvSearch);\r\n");
      out.write("	        $.ajax({\r\n");
      out.write("	            url: \"/test/showRegister\",\r\n");
      out.write("	            type: \"get\",\r\n");
      out.write("	            data: {\r\n");
      out.write("	                masv: masvSearch\r\n");
      out.write("	            },\r\n");
      out.write("	            beforeSend: function () {\r\n");
      out.write("	                $('#ajax-loader').show();\r\n");
      out.write("	            },\r\n");
      out.write("	            success: function (data) {\r\n");
      out.write("	                $('#ajax-loader').hide();\r\n");
      out.write("	                var row = document.getElementById(\"info_student\");\r\n");
      out.write("	                row.innerHTML = data;\r\n");
      out.write("	            },\r\n");
      out.write("	            error: function (xhr) {\r\n");
      out.write("	                //Do Something to handle error\r\n");
      out.write("	            }\r\n");
      out.write("	        });\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	    \r\n");
      out.write("	    var input = document.getElementById(\"masv\");\r\n");
      out.write("	    input.addEventListener(\"keypress\", function (event) {\r\n");
      out.write("	        if (event.key === \"Enter\") {\r\n");
      out.write("	            if (input.value == \"\") {\r\n");
      out.write("	                alert(\"Vui lòng nhập mã sinh viên!\");\r\n");
      out.write("	            } else {\r\n");
      out.write("	                event.preventDefault();\r\n");
      out.write("	                document.getElementById(\"search\").click();\r\n");
      out.write("	            }\r\n");
      out.write("	        }\r\n");
      out.write("	    });\r\n");
      out.write("	    var btn = document.getElementById(\"search\");\r\n");
      out.write("	    btn.addEventListener('click', function () {\r\n");
      out.write("	        if (input.value == \"\") {\r\n");
      out.write("	            alert(\"Vui lòng nhập mã sinh viên!\");\r\n");
      out.write("	        } else {\r\n");
      out.write("	            searchSVAjax();\r\n");
      out.write("	        }\r\n");
      out.write("	    })\r\n");
      out.write("  // 	    	    function displayClock() {\r\n");
      out.write("  //   setInterval(displayClock, 1000);\r\n");
      out.write("  //   var date = new Date();\r\n");
      out.write("  //   var dateNow = \"Ngày \"+ date.getDate()+' tháng '+(date.getMonth()+1)+' năm '+date.getFullYear();\r\n");
      out.write("  //   var hrs = date.getHours();\r\n");
      out.write("  //   var min = date.getMinutes();\r\n");
      out.write("  //   var sec = date.getSeconds();\r\n");
      out.write("  //   var en =\"AM\";\r\n");
      out.write("  //   if (hrs > 12) {\r\n");
      out.write("  //       en=\"PM\";\r\n");
      out.write("  //     }\r\n");
      out.write("  //   if (hrs > 12) {\r\n");
      out.write("  //     hrs = hrs - 12;\r\n");
      out.write("  //   }\r\n");
      out.write("  //   if (hrs == 0) {\r\n");
      out.write("  //     hrs = 12;\r\n");
      out.write("  //   }\r\n");
      out.write("  //   if (hrs<10) {\r\n");
      out.write("	// 	hrs='0'+hrs;\r\n");
      out.write("	// }\r\n");
      out.write("  //   if (min<10) {\r\n");
      out.write("	// 	min='0'+min;\r\n");
      out.write("	// }\r\n");
      out.write("  //   if (sec<10) {\r\n");
      out.write("	// 	sec='0'+sec;\r\n");
      out.write("	// }\r\n");
      out.write("  //   const timeText = document.getElementById(\"timeNow\");\r\n");
      out.write("	// timeText.innerHTML=hrs+':'+min+':'+sec+' '+en+ ' ' +Intl.DateTimeFormat().resolvedOptions().timeZone +' '+dateNow;\r\n");
      out.write("  //}\r\n");
      out.write("	    //displayClock();\r\n");
      out.write("	    \r\n");
      out.write("	    function showPayment() {\r\n");
      out.write("	    \r\n");
      out.write("	      const value1 = document.getElementById(\"ngaybatdau\").value;\r\n");
      out.write("	      const value2 = document.getElementById(\"ngayketthuc\").value;\r\n");
      out.write("	      const phong = document.getElementById(\"phong\").value;\r\n");
      out.write("	      const loaiphong = document.getElementById(\"loaiphong\").value;\r\n");
      out.write("	      const hocki = document.getElementById(\"hocki\").value;\r\n");
      out.write("	      var phivesinh = 0;\r\n");
      out.write("	      var tienphong=0;\r\n");
      out.write("	      var tien='';\r\n");
      out.write("	      const date1 = new Date(value1);\r\n");
      out.write("	      const date2 = new Date(value2);\r\n");
      out.write("	      const diffTime = Math.abs(date2 - date1);\r\n");
      out.write("	      const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));\r\n");
      out.write("	      const month = Math.floor(diffDays / 30);\r\n");
      out.write("	      const day = diffDays % 30;\r\n");
      out.write("	      const payment = document.getElementById(\"payment\"); \r\n");
      out.write("	      if (loaiphong==\"Phòng thường (8 giường)\" || loaiphong==\"Phòng CBGV\") {\r\n");
      out.write("	    	  tienphong=100000 * month + day * (100000/30);\r\n");
      out.write("	    	  tien='100.000/tháng';\r\n");
      out.write("		} else if (loaiphong==\"Phòng dịch vụ (3 giường)\") {\r\n");
      out.write("			 tienphong=700000 * month + day * (700000/30);\r\n");
      out.write("			 tien='700.000/tháng';\r\n");
      out.write("		}\r\n");
      out.write("	      phivesinh=30000** month + day * (30000/30);\r\n");
      out.write("	      console.log(phivesinh);\r\n");
      out.write("	      const tiennuoc = 27440 * month + day*(27440/30);\r\n");
      out.write("	      const tong = tiennuoc + tienphong+phivesinh;\r\n");
      out.write("	      var data = '<tr>' +\r\n");
      out.write("	      '<td>' + loaiphong + '</td>' +\r\n");
      out.write("	      '<td>'+tien+'</td>' +\r\n");
      out.write("	      '<td rowspan=\"3\">' + value1 + ' đến ' + value2 + '(' + month + ' tháng ' +day+' ngày)' + '</td>' +\r\n");
      out.write("	      '<td>' + Math.round(tienphong * 100.0) / 100.0 + '</td>' +\r\n");
      out.write("	      '<td> 0 </td>' +\r\n");
      out.write("	      '<td>' + Math.round(tienphong * 100.0) / 100.0 + '</td>' +\r\n");
      out.write("	      '</tr>' +\r\n");
      out.write("	      '<tr>' +\r\n");
      out.write("	      '<td> Tiền điện </td>' +\r\n");
      out.write("	      '<td> 2.009,7/số </td>' +\r\n");
      out.write("	      '<td> Theo thực tế sử dụng </td>' +\r\n");
      out.write("	      '<td> </td>' +\r\n");
      out.write("	      '<td> </td>' +\r\n");
      out.write("	      '</tr>' +\r\n");
      out.write("	      '<tr>' +\r\n");
      out.write("	      '<td> Tiền nước </td>' +\r\n");
      out.write("	      '<td> 27.440/tháng </td>' +\r\n");
      out.write("	      '<td>' + Math.round(tiennuoc * 100.0) / 100.0 + '</td>' +\r\n");
      out.write("	      '<td> 0 </td>' +\r\n");
      out.write("	      '<td>' + Math.round(tiennuoc * 100.0) / 100.0 + '</td>' +\r\n");
      out.write("	      '</tr>' +\r\n");
      out.write("	      '<tr>' +\r\n");
      out.write("	      '<td> Phí vệ sinh </td>' +\r\n");
      out.write("	      '<td> 30.000/tháng </td>' +\r\n");
      out.write("	      '<td> </td>' +\r\n");
      out.write("	      '<td> '+phivesinh+' </td>' +\r\n");
      out.write("	      '<td> 0 </td>' +\r\n");
      out.write("	      '<td> '+phivesinh+' </td>' +\r\n");
      out.write("	      '</tr>' +\r\n");
      out.write("	      '<tr>' +\r\n");
      out.write("	      '<td>Tổng tiền</td>'+\r\n");
      out.write("	      '<td colspan=\"3\">' + Math.round(tong * 100.0) / 100.0 +' đ'+ '</td>' +\r\n");
      out.write("	      '</tr>';\r\n");
      out.write("\r\n");
      out.write("	      console.log(data);\r\n");
      out.write("	if (value1=='' || value2=='' || phong==''|| loaiphong=='' || hocki=='') {\r\n");
      out.write("		alert('Chưa nhập đầy đủ dữ liệu!');\r\n");
      out.write("	} else {\r\n");
      out.write("	      payment.innerHTML = data;\r\n");
      out.write("	}\r\n");
      out.write("	    }\r\n");
      out.write("	    \r\n");
      out.write("	  </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /register-live.jsp(76,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc.isUser==1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<li class=\"nav-item dropdown\"><a\r\n");
          out.write("						class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\"\r\n");
          out.write("						role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Đăng\r\n");
          out.write("							ký</a>\r\n");
          out.write("						<div class=\"dropdown-menu\">\r\n");
          out.write("							<a class=\"dropdown-item\" href=\"register-live.jsp\">Đăng ký ở\r\n");
          out.write("								nội trú</a> <a class=\"dropdown-item\"\r\n");
          out.write("								href=\"register-infor-student.jsp\">Đăng ký thông tin cá nhân</a>\r\n");
          out.write("						</div></li>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /register-live.jsp(88,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc.isAdmin==3}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<li class=\"nav-item dropdown\"><a\r\n");
          out.write("						class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\"\r\n");
          out.write("						role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Quản\r\n");
          out.write("							lý</a>\r\n");
          out.write("						<div class=\"dropdown-menu\">\r\n");
          out.write("							<a class=\"dropdown-item\" href=\"quanlySV\">Quản lý sinh viên</a> <a\r\n");
          out.write("								class=\"dropdown-item\" href=\"quanlyPhong\">Quản lý phòng</a> <a\r\n");
          out.write("								class=\"dropdown-item\" href=\"quanlyAcc\">Quản lý tài khoản</a>\r\n");
          out.write("						</div></li>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /register-live.jsp(100,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc.isUser==1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("					<li class=\"nav-item dropdown\"><a\r\n");
          out.write("						class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\"\r\n");
          out.write("						role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Cập\r\n");
          out.write("							nhật thông tin</a>\r\n");
          out.write("						<div class=\"dropdown-menu\">\r\n");
          out.write("							<a class=\"dropdown-item\" href=\"editLiver.jsp\">Cập nhật thông\r\n");
          out.write("								tin ở nội trú</a> <a class=\"dropdown-item\" href=\"editInfor.jsp\">Cập\r\n");
          out.write("								nhật thông tin cá nhân</a>\r\n");
          out.write("						</div></li>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /register-live.jsp(113,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc.isAdmin==3}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<li class=\"nav-item dropdown\"><a\r\n");
          out.write("						class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\"\r\n");
          out.write("						role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Thông\r\n");
          out.write("							báo</a>\r\n");
          out.write("						<div class=\"dropdown-menu\">\r\n");
          out.write("							<a class=\"dropdown-item\" href=\"\">Duyệt đăng ký phòng</a> <a\r\n");
          out.write("								class=\"dropdown-item\" href=\"\">Liên lạc sinh viên, phụ huynh</a>\r\n");
          out.write("							<a class=\"dropdown-item\" href=\"\">Thông báo nộp tiền</a> <a\r\n");
          out.write("								class=\"dropdown-item\" href=\"\">Thông báo hết hạn</a>\r\n");
          out.write("						</div></li>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /register-live.jsp(126,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc.isAdmin==1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"dashboard.jsp\">Đến\r\n");
          out.write("							trang quản lý</a></li>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /register-live.jsp(131,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc.isUser==1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<li class=\"nav-item dropdown\"><a\r\n");
          out.write("						class=\"nav-link dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\"\r\n");
          out.write("						role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Biểu\r\n");
          out.write("							mẫu</a>\r\n");
          out.write("						<div class=\"dropdown-menu\">\r\n");
          out.write("							<a class=\"dropdown-item\" href=\"file1.jsp\" target=\"_blank\">Đơn\r\n");
          out.write("								đăng ký ở nội trú</a> <a class=\"dropdown-item\" href=\"file2.jsp\"\r\n");
          out.write("								target=\"_blank\">Hợp đồng</a> <a class=\"dropdown-item\"\r\n");
          out.write("								href=\"file3.jsp\" target=\"_blank\">Quy định</a>\r\n");
          out.write("						</div></li>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent(null);
      // /register-live.jsp(144,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Xin chào\r\n");
          out.write("							");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" !</a></li>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f7_reused = false;
    try {
      _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f7.setParent(null);
      // /register-live.jsp(149,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc==null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
      if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<ul class=\"nav navbar-nav navbar-right\">\r\n");
          out.write("					<li><a href=\"login\"><i\r\n");
          out.write("							class=\"fa-solid fa-right-to-bracket\"></i>Đăng nhập</a></li>\r\n");
          out.write("				</ul>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      _jspx_th_c_005fif_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f8 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f8_reused = false;
    try {
      _jspx_th_c_005fif_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f8.setParent(null);
      // /register-live.jsp(155,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f8.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.acc!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f8 = _jspx_th_c_005fif_005f8.doStartTag();
      if (_jspx_eval_c_005fif_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<ul class=\"nav navbar-nav navbar-right\">\r\n");
          out.write("					<li><a href=\"logout\"><i\r\n");
          out.write("							class=\"fa-solid fa-right-to-bracket\"></i>Đăng xuất</a></li>\r\n");
          out.write("				</ul>\r\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fif_005f8.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f8);
      _jspx_th_c_005fif_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f8, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f8_reused);
    }
    return false;
  }
}
