/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2022-07-07 20:55:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sendMessage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/style.css", Long.valueOf(1657208816345L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>contact form</title>\r\n");
      out.write("<style>");
      out.write("@import\r\n");
      out.write("	url('https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap')\r\n");
      out.write("	;\r\n");
      out.write("\r\n");
      out.write("html {\r\n");
      out.write("	scroll-behavior: smooth;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-primary {\r\n");
      out.write("	color: #fff !important;\r\n");
      out.write("	background-color: #FF6A3D !important;\r\n");
      out.write("	border-color: #FF6A3D !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2 {\r\n");
      out.write("	font-size: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".center {\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".preloading {\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	background: #ffffff no-repeat center center !important;\r\n");
      out.write("	background-size: 10%;\r\n");
      out.write("	z-index: 9999;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".divider:after, .divider:before {\r\n");
      out.write("	content: \"\";\r\n");
      out.write("	flex: 1;\r\n");
      out.write("	height: 1px;\r\n");
      out.write("	background: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p {\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=submit] {\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span {\r\n");
      out.write("	color: red !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span {\r\n");
      out.write("	color: red;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-light .navbar-nav .nav-link, #navbarColor03>ul.nav.navbar-nav.navbar-right>li>a\r\n");
      out.write("	{\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul li a {\r\n");
      out.write("	font-family: \"bebasneue\", Tahoma, Arial, sans-serif !important;\r\n");
      out.write("	text-transform: uppercase;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbarColor03>ul.nav.navbar-nav.navbar-right>li>a>i:before {\r\n");
      out.write("	padding: 3px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbarColor03>form {\r\n");
      out.write("	width: 130px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navbarColor03>form>div>a {\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover {\r\n");
      out.write("	text-decoration: none !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body>div>div>form>div>div:nth-child(4)>a {\r\n");
      out.write("	width: 370px;\r\n");
      out.write("	height: 29px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn:after {\r\n");
      out.write("	padding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-default {\r\n");
      out.write("	color: #ffffff;\r\n");
      out.write("	background-color: #a7a9aa;\r\n");
      out.write("	border-color: #a7a9aa;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	height: 55px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	height: 45px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	background-size: 300% 100%;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	moz-transition: all .4s ease-in-out;\r\n");
      out.write("	-o-transition: all .4s ease-in-out;\r\n");
      out.write("	-webkit-transition: all .4s ease-in-out;\r\n");
      out.write("	transition: all .4s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn:hover {\r\n");
      out.write("	background-position: 100% 0;\r\n");
      out.write("	moz-transition: all .4s ease-in-out;\r\n");
      out.write("	-o-transition: all .4s ease-in-out;\r\n");
      out.write("	-webkit-transition: all .4s ease-in-out;\r\n");
      out.write("	transition: all .4s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn:focus {\r\n");
      out.write("	outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("	background-image: linear-gradient(to right, #f5ce62, #e43603, #fa7199, #e85a19);\r\n");
      out.write("	box-shadow: 0 4px 15px 0 rgba(229, 66, 10, 0.75);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".modal-content {\r\n");
      out.write("	position: static;\r\n");
      out.write("	float: left;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	width: 1000px;\r\n");
      out.write("	background: #ffffff;\r\n");
      out.write("	box-shadow: 0px 3px 6px rgb(34 25 25/ 40%);\r\n");
      out.write("	padding: 0px 30px;\r\n");
      out.write("	min-height: 100%;\r\n");
      out.write("	cursor: default;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".img-thumbnail {\r\n");
      out.write("	width: 100px;\r\n");
      out.write("	height: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Dashboard */\r\n");
      out.write("body {\r\n");
      out.write("	background-color: #fbfbfb;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( min-width : 991.98px) {\r\n");
      out.write("	main {\r\n");
      out.write("		padding-left: 240px;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Sidebar */\r\n");
      out.write(".sidebar {\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	bottom: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	padding: 58px 0 0; /* Height of navbar */\r\n");
      out.write("	box-shadow: 0 2px 5px 0 rgb(0 0 0/ 5%), 0 2px 10px 0 rgb(0 0 0/ 5%);\r\n");
      out.write("	width: 240px;\r\n");
      out.write("	z-index: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width : 991.98px) {\r\n");
      out.write("	.sidebar {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar .active {\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	box-shadow: 0 2px 5px 0 rgb(0 0 0/ 16%), 0 2px 10px 0 rgb(0 0 0/ 12%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar-sticky {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	height: calc(100vh - 48px);\r\n");
      out.write("	padding-top: 0.5rem;\r\n");
      out.write("	overflow-x: hidden;\r\n");
      out.write("	overflow-y: auto;\r\n");
      out.write("	/* Scrollable contents if viewport is shorter than content. */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img.anhthe {\r\n");
      out.write("	width: 113px;\r\n");
      out.write("	height: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button {\r\n");
      out.write("	margin-left: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("hr {\r\n");
      out.write("	border: 1px solid blue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("	background-color: #fbfbfb;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=checkbox], input[type=radio] {\r\n");
      out.write("	/* box-sizing: border-box; */\r\n");
      out.write("	font-size: 5px;\r\n");
      out.write("	margin: 0 10px 0 10px;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	width: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn {\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	height: 33px !important;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	height: 45px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	background-size: 300% 100%;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	moz-transition: all .4s ease-in-out;\r\n");
      out.write("	-o-transition: all .4s ease-in-out;\r\n");
      out.write("	-webkit-transition: all .4s ease-in-out;\r\n");
      out.write("	transition: all .4s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn:hover {\r\n");
      out.write("	background-position: 100% 0;\r\n");
      out.write("	moz-transition: all .4s ease-in-out;\r\n");
      out.write("	-o-transition: all .4s ease-in-out;\r\n");
      out.write("	-webkit-transition: all .4s ease-in-out;\r\n");
      out.write("	transition: all .4s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn:focus {\r\n");
      out.write("	outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-success {\r\n");
      out.write("	background-image: linear-gradient(to right, #25aae1, #40e495, #30dd8a, #2bb673);\r\n");
      out.write("	box-shadow: 0 4px 15px 0 rgba(49, 196, 190, 0.75);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-default {\r\n");
      out.write("	background-image: linear-gradient(to right, #ed6ea0, #ec8c69, #f7186a, #FBB03B);\r\n");
      out.write("	box-shadow: 0 4px 15px 0 rgba(236, 116, 149, 0.75);\r\n");
      out.write("}\r\n");
      out.write("/* Dashboard */");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<link href=\"contact-form.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("	<div class=\"fcf-body\">\r\n");
      out.write("\r\n");
      out.write("		<div id=\"fcf-form\">\r\n");
      out.write("			<h3 class=\"fcf-h3\">Gửi thông báo</h3>\r\n");
      out.write("\r\n");
      out.write("			<form id=\"fcf-form-id\" class=\"fcf-form-class\" method=\"post\"\r\n");
      out.write("				action=\"./sendMsg\">\r\n");
      out.write("				<div class=\"fcf-form-group\">\r\n");
      out.write("					<label for=\"Name\" class=\"fcf-label\">Người nhận</label>\r\n");
      out.write("					<div class=\"fcf-input-group\">\r\n");
      out.write("						<input type=\"text\" id=\"user\" name=\"user\" class=\"fcf-form-control\"\r\n");
      out.write("							required>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"fcf-form-group\">\r\n");
      out.write("					<label for=\"Email\" class=\"fcf-label\">Tiêu đề</label>\r\n");
      out.write("					<div class=\"fcf-input-group\">\r\n");
      out.write("						<input type=\"text\" id=\"title\" name=\"title\"\r\n");
      out.write("							class=\"fcf-form-control\" required>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"fcf-form-group\">\r\n");
      out.write("					<label for=\"Message\" class=\"fcf-label\">Nội dung</label>\r\n");
      out.write("					<div class=\"fcf-input-group\">\r\n");
      out.write("						<textarea id=\"msg\" name=\"msg\" class=\"fcf-form-control\" rows=\"6\"\r\n");
      out.write("							maxlength=\"3000\" required></textarea>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"fcf-form-group\">\r\n");
      out.write("					<button type=\"submit\" id=\"fcf-button\"\r\n");
      out.write("						class=\"fcf-btn fcf-btn-primary fcf-btn-lg fcf-btn-block\">Gửi</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
