/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2022-07-07 01:32:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class startchart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    ");
String uname=(String)session.getAttribute("name"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <head>\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("        <script type=\"text/javascript\" src=\"./js/check.js\"></script>\r\n");
      out.write("        <title>The Chat Room</title>\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"icon.jpeg\" />\r\n");
      out.write("    <style>\r\n");
      out.write("    div.middle {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  width: 60%;\r\n");
      out.write("  height: 20%;\r\n");
      out.write("  z-index: 15;\r\n");
      out.write("  top: 50%;\r\n");
      out.write("  left: 41%;\r\n");
      out.write("  margin: -100px 0 0 -150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".always-middle\r\n");
      out.write("{\r\n");
      out.write("    border: solid 1px black;\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("    z-index: 100;\r\n");
      out.write("\r\n");
      out.write("    height: 400px;\r\n");
      out.write("    margin-top: -200px;\r\n");
      out.write("\r\n");
      out.write("    width: 600px;\r\n");
      out.write("    margin-left: -300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logout-chat{\r\n");
      out.write("\r\n");
      out.write(" background-color: brown;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    height: 5%;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div#list {\r\n");
      out.write("  background-color: grey;\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    left: 19%;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    color: #000;\r\n");
      out.write("  overflow: scroll;\r\n");
      out.write("  padding: 25px;\r\n");
      out.write("  width: 80%;\r\n");
      out.write("  height: 50%;\r\n");
      out.write("  z-index: 15;\r\n");
      out.write("  margin: -100px 0 0 -150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("g{\r\n");
      out.write(" color: white;\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("        background-image: url(bg.gif);\r\n");
      out.write("        background-position:top center;\r\n");
      out.write("        background-attachment:fixed;\r\n");
      out.write("        color: lightgray;\r\n");
      out.write("     }\r\n");
      out.write("a\r\n");
      out.write("  {\r\n");
      out.write("  color: lightgray;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write(".textbox\r\n");
      out.write("    {\r\n");
      out.write("     width:300px;\r\n");
      out.write("     height: 40px;\r\n");
      out.write("     font-size: 20px;\r\n");
      out.write("    border-radius: 50px;\r\n");
      out.write("    border: 5px solid gray;\r\n");
      out.write("     background-color: #6D6D6D;\r\n");
      out.write("      outline: none;\r\n");
      out.write("    color: black\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write(".circle{\r\n");
      out.write("    height: 35px;\r\n");
      out.write("    width: 85px;\r\n");
      out.write("    border-radius: 50px;\r\n");
      out.write("    border: 5px solid green;\r\n");
      out.write("    background-color: #22B14C;\r\n");
      out.write("    color: black;\r\n");
      out.write("}\r\n");
      out.write("    </style>\r\n");
      out.write("    <script>\r\n");
      out.write("     setInterval(reloaddata, 3000);\r\n");
      out.write("    </script>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <p id=\"result\"></p>\r\n");
      out.write("        Welcome, ");
      out.print(uname);
      out.write("\r\n");
      out.write("        <div class=\"logout-div\" align=\"right\"><a href=\"logout.jsp\" class=\"logout-chat\">Logout</a></div>\r\n");
      out.write("        <div id=\"list\">\r\n");
      out.write("            <div id=\"content\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <input style=\"display: none\" type=\"text\" id=\"u\" value=\"");
      out.print(uname);
      out.write("\">\r\n");
      out.write("            <textarea id='h' style=\"width: 100%; height: 10%;\"></textarea>\r\n");
      out.write("            <input type=\"button\" value=\"send\" onclick=\"addText()\" />\r\n");
      out.write("        </div>\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
